### PR TITLE
Effective ways to attract developers to your company

### PR DESCRIPTION
**Pull request by rich-zhao-wei**
Team, please let me know if you have any feedback. Thanks. @cheney0221 @ruopiao @arthurh123

### CODE REVIEW

**Comment by arthurh123** [comment]
I love the things you've mentioned and the article you shared in your link! It's also a very helpful article. Since I was working as an engineer before, and great to hear the ideas from the other side of the table.

**Comment by rich-zhao-wei** [comment]
Many thanks to all for providing valuable comments. Given the positive feedback on the shared article, I'd like to contribute another article with link updated in the file. Happy Sunday reading!

**Comment by arthurh123** [comment]
👍👍

**Comment by cheney0221** [comment]
:+1:

**Pull request closed without merging**
